### ISSUE TITLE
Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release.

### ISSUE THREAD

**Issue by Axolem** [SahilAggarwal2004/react-reorder-list#1]

**Comment by SahilAggarwal2004** [comment]
Hi @Axolem,

Thanks for bringing this up! I see that React 19 has changed how ref is handled, and it's now a regular prop. Since we're trying to maintain support for both React 18 and React 19, I wanted to ask if you know of a good way to handle this change while keeping compatibility for both versions.

Do you have any suggestions or a workaround that you've found effective for this? I'd appreciate your input!

**Comment by SahilAggarwal2004** [comment]
Hi @Axolem,

Thanks for pointing this out! As of v0.8.0, we've dropped support for React v18 in favor of React v19. With React 19 now handling `ref` as a regular prop, this change is now aligned with the latest version. Since we're no longer supporting React v18, this should no longer be an issue.

Appreciate you bringing this up!
